### ISSUE TITLE
Greasy Fork Update stuck on old version 2020.6.14

### ISSUE THREAD

**Issue by lethak** [lethak/digitally_imported_userscript#47]
https://greasyfork.org/en/scripts/397697-diuserscript-for-audioaddict-platforms

`Script sync failed - Code is too long (maximum is 2000000 characters).`

Also, GF removes @downloadURL and @updateURL from the installed script ... nasty platform.

## TODO

- [x] Review whole install process
- [x] Display a "deprecated version is running" notification
- [x] Trim unnecessary code & libraries
- [x] Create a Greasy Fork custom build?

**Comment by lethak** [comment]
https://github.com/lethak/LTKDIFMU-userscript/blob/v2022.2.4/doc/greasyforks/README.md
